/* TravelBook Pro Mobile v1.0 — datos locales, sin dependencias externas */
const KEY = "travelbook-pro-mobile-data-v1";
const initialData = { version: 1, trips: [] };
let data = loadData();
let route = { page: "dashboard", tripId: null, tab: "days" };
let deferredInstall = null;
const app = document.querySelector("#app");
const modalLayer = document.querySelector("#modalLayer");

function loadData() {
  try {
    const parsed = JSON.parse(localStorage.getItem(KEY));
    if (parsed && Array.isArray(parsed.trips)) return parsed;
  } catch (_) { /* se inicia una base nueva si la copia local está dañada */ }
  return structuredClone(initialData);
}
function save() { localStorage.setItem(KEY, JSON.stringify(data)); }
function uid() { return crypto.randomUUID ? crypto.randomUUID() : `${Date.now()}-${Math.random().toString(16).slice(2)}`; }
function esc(value = "") { return String(value).replace(/[&<>'"]/g, c => ({ "&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;" })[c]); }
function money(value = 0) { return new Intl.NumberFormat("es-ES", { style: "currency", currency: "EUR" }).format(Number(value) || 0); }
function dateLabel(date) { if (!date) return "Sin fecha"; return new Intl.DateTimeFormat("es-ES", { day:"numeric", month:"short", year:"numeric" }).format(new Date(`${date}T12:00:00`)); }
function shortDate(date) { if (!date) return "—"; return new Intl.DateTimeFormat("es-ES", { day:"numeric", month:"short" }).format(new Date(`${date}T12:00:00`)); }
function daysBetween(start, end) { if (!start || !end) return 0; return Math.max(1, Math.round((new Date(`${end}T12:00`) - new Date(`${start}T12:00`)) / 86400000) + 1); }
function tripById(id) { return data.trips.find(t => t.id === id); }
function allActivities() { return data.trips.flatMap(t => (t.activities || []).map(a => ({ ...a, trip: t }))).sort((a,b) => `${a.date}${a.time || ""}`.localeCompare(`${b.date}${b.time || ""}`)); }
function allExpenses() { return data.trips.flatMap(t => (t.expenses || []).map(e => ({ ...e, trip: t }))).sort((a,b) => (b.date || "").localeCompare(a.date || "")); }
function statusClass(status) { return ({ "Confirmado":"confirmado", "Completado":"completado" }[status] || "preparacion"); }
function iconFor(text) { const v = text.toLowerCase(); if (/vuelo|avión|transporte|tren/.test(v)) return "✈"; if (/gasolina|parking|peaje|tasa/.test(v)) return "🚗"; if (/hotel|alojamiento/.test(v)) return "⌂"; if (/comida|restaurante/.test(v)) return "🍴"; if (/bebida/.test(v)) return "🥤"; if (/supermercado/.test(v)) return "🛒"; if (/souvenir/.test(v)) return "🎁"; if (/compra/.test(v)) return "🛍"; if (/museo|visita|actividad/.test(v)) return "⌾"; return "⌖"; }
function toast(message) { const el = document.querySelector("#toast"); el.textContent = message; el.classList.add("show"); clearTimeout(toast.timer); toast.timer = setTimeout(() => el.classList.remove("show"), 2800); }

function render() {
  const page = route.page;
  app.innerHTML = page === "dashboard" ? dashboardView() : page === "trips" ? tripsView() : page === "activity" ? activitiesView() : page === "expenses" ? expensesView() : page === "more" ? moreView() : page === "trip" ? tripView() : dashboardView();
  document.querySelectorAll(".nav-item").forEach(item => item.classList.toggle("active", item.dataset.page === page || (page === "trip" && item.dataset.page === "trips")));
  window.scrollTo({ top: 0, behavior: "instant" });
}
function heading(title, subtitle = "") { return `<div class="page-heading"><div><h1>${esc(title)}</h1>${subtitle ? `<p>${esc(subtitle)}</p>` : ""}</div></div>`; }
function empty(icon, title, text, action, label) { return `<div class="card empty"><span class="empty-icon">${icon}</span><h3>${esc(title)}</h3><p>${esc(text)}</p>${action ? `<button class="button" data-action="${action}">${esc(label)}</button>` : ""}</div>`; }

function dashboardView() {
  const trips = data.trips;
  const activities = allActivities();
  const expenses = allExpenses();
  const total = expenses.reduce((sum, e) => sum + Number(e.amount || 0), 0);
  const upcoming = [...trips].filter(t => t.status !== "Completado").sort((a,b) => (a.start || "9999").localeCompare(b.start || "9999")).slice(0,3);
  return `
    <section class="hero"><div class="eyebrow">Tu diario de viajes</div><h1>¡Hola!</h1><p>Planifica tus rutas, guarda tus recuerdos y controla tu presupuesto.</p></section>
    <div class="quick-row"><button class="quick-action" data-action="new-trip"><span>✈</span>Nuevo viaje</button><button class="quick-action" data-page="activity"><span>◷</span>Agenda</button><button class="quick-action" data-page="expenses"><span>€</span>Gastos</button><button class="quick-action" data-page="more"><span>⇧</span>Exportar</button></div>
    <div class="stats"><div class="stat-card"><div class="stat-icon">✈</div><span class="stat-value">${trips.length}</span><span class="stat-label">Viajes</span></div><div class="stat-card"><div class="stat-icon">▣</div><span class="stat-value">${trips.reduce((n,t) => n + (t.days || []).length, 0)}</span><span class="stat-label">Días planificados</span></div><div class="stat-card"><div class="stat-icon">⌾</div><span class="stat-value">${activities.length}</span><span class="stat-label">Actividades</span></div><div class="stat-card"><div class="stat-icon">€</div><span class="stat-value">${money(total)}</span><span class="stat-label">Total gastado</span></div></div>
    <section class="section"><h2 class="section-title">Próximos viajes</h2>${upcoming.length ? `<div class="card trip-list">${upcoming.map(tripRow).join("")}</div>` : empty("✈", "Tu próximo viaje empieza aquí", "Crea un viaje y tendrás a mano su agenda, actividades y gastos.", "new-trip", "Crear viaje")}</section>
    ${expenses.length ? `<section class="section"><h2 class="section-title">Resumen de gastos</h2>${expenseSummary(expenses)}</section>` : ""}
    <section class="section"><h2 class="section-title">Últimas actividades</h2>${activities.length ? `<div class="card activity-list">${activities.slice(-4).reverse().map(activityRow).join("")}</div>` : `<div class="info-note">Cuando añadas actividades a tus días de viaje, aparecerán aquí como una agenda rápida.</div>`}</section>`;
}
function tripRow(t) { return `<button class="trip-row" data-action="open-trip" data-id="${t.id}"><span class="trip-thumb">${iconFor(t.destination || t.name)}</span><span class="row-copy"><span class="row-title">${esc(t.name)}</span><span class="row-sub">${esc(t.destination || "Destino por definir")} · ${t.start ? `${shortDate(t.start)} – ${shortDate(t.end)}` : "Sin fechas"}</span></span><span class="pill ${statusClass(t.status)}">${esc(t.status || "En preparación")}</span></button>`; }
function expenseTotals(expenses) { const totals = {}; expenses.forEach(e => totals[e.category || "Otros"] = (totals[e.category || "Otros"] || 0) + Number(e.amount || 0)); return Object.entries(totals).sort((a,b) => b[1] - a[1]); }
function expenseSummary(expenses) { const rows = expenseTotals(expenses); const total = rows.reduce((sum, [, amount]) => sum + amount, 0); const colors=["#0878d1","#f39a19","#10a66a","#8d5ce9","#ec5b65","#19a9b8","#c876e4","#719341","#e66b45","#4479ce","#a68532","#5d83a8","#cc5b85"]; let point=0; const segments=rows.map(([, amount], index) => { const start=point; point += total ? amount / total * 100 : 0; return `${colors[index % colors.length]} ${start}% ${point}%`; }).join(","); return `<div class="card category-chart"><div class="donut" style="background:conic-gradient(${segments || "#0878d1 0 100%"})"></div><div class="legend">${rows.map(([category, amount], index) => `<div><span><i style="background:${colors[index % colors.length]}"></i>${esc(category)}</span><b>${money(amount)} · ${total ? Math.round(amount / total * 100) : 0}%</b></div>`).join("")}</div></div>`; }

function tripsView() {
  const trips = [...data.trips].sort((a,b) => (a.start || "9999").localeCompare(b.start || "9999"));
  return `${heading("Mis viajes", `${trips.length} ${trips.length === 1 ? "viaje" : "viajes"} guardados`)}<div class="filter-bar"><button class="active" data-filter="all">Todos</button><button data-filter="En preparación">En preparación</button><button data-filter="Confirmado">Confirmados</button><button data-filter="Completado">Completados</button></div><div id="tripsList">${trips.length ? trips.map(tripCard).join("") : empty("🧳", "Aún no hay viajes", "Crea tu primer viaje para empezar a organizarlo.", "new-trip", "Nuevo viaje")}</div><button class="fab" data-action="new-trip" aria-label="Añadir viaje">+</button>`;
}
function tripCard(t) { const amount = (t.expenses || []).reduce((s,e) => s + Number(e.amount || 0), 0); return `<article class="card trip-card" data-trip-status="${esc(t.status || "En preparación")}"><div class="trip-card-top"><span class="trip-thumb">${iconFor(t.destination || t.name)}</span><div class="row-copy"><h2>${esc(t.name)}</h2><div class="row-sub">${esc(t.destination || "Destino por definir")}</div><div class="row-sub">${t.start ? `${dateLabel(t.start)} — ${dateLabel(t.end)}` : "Fechas por definir"}</div></div><span class="pill ${statusClass(t.status)}">${esc(t.status || "En preparación")}</span></div><div class="trip-meta"><span>▣ ${(t.days || []).length} días</span><span>⌾ ${(t.activities || []).length} actividades</span><span>€ ${money(amount)}</span></div><div class="trip-actions"><button class="button secondary small" data-action="open-trip" data-id="${t.id}">Abrir</button><button class="button secondary small" data-action="edit-trip" data-id="${t.id}">Editar</button></div></article>`; }

function activitiesView() { const activities = allActivities(); return `${heading("Agenda", "Todas tus actividades en un solo sitio")}${activities.length ? `<div class="card activity-list">${activities.map(activityRow).join("")}</div>` : empty("◷", "Agenda vacía", "Añade actividades dentro de un viaje para organizar cada día.", "go-trips", "Ir a viajes")}`; }
function activityRow(a) { return `<div class="activity-row"><span class="round-icon">${iconFor(a.title || "")}</span><div class="row-copy"><div class="row-title">${esc(a.title)}</div><div class="row-sub">${esc(a.trip ? a.trip.name : "")} · ${a.date ? shortDate(a.date) : "Sin fecha"}${a.time ? ` · ${esc(a.time)}` : ""}${a.location ? ` · ${esc(a.location)}` : ""}</div></div>${a.trip ? `<button class="inline-actions" data-action="open-trip" data-id="${a.trip.id}" aria-label="Abrir viaje">›</button>` : ""}</div>`; }
function expensesView() { const expenses = allExpenses(); const total = expenses.reduce((s,e) => s + Number(e.amount || 0), 0); return `${heading("Gastos", `${money(total)} registrados`)}${expenses.length ? `<section class="section"><h2 class="section-title">Desglose por categoría</h2>${expenseSummary(expenses)}</section><section class="section"><h2 class="section-title">Todos los gastos</h2><div class="card expense-list">${expenses.map(expenseRow).join("")}</div></section>` : empty("€", "Sin gastos todavía", "Registra los gastos desde la ficha de cada viaje.", "go-trips", "Ir a viajes")}`; }
function expenseRow(e) { return `<div class="expense-row"><span class="round-icon">${iconFor(e.category || "")}</span><div class="row-copy"><div class="row-title">${esc(e.description || e.category || "Gasto")}</div><div class="row-sub">${esc(e.trip ? e.trip.name : "")} · ${esc(e.category || "Otros")}${e.date ? ` · ${shortDate(e.date)}` : ""}</div></div><span class="expense-amount">${money(e.amount)}</span>${e.trip ? `<button class="inline-actions" data-action="open-trip" data-id="${e.trip.id}" aria-label="Abrir viaje">›</button>` : ""}</div>`; }

function moreView() { return `${heading("Más", "Herramientas y tus datos")}
  <div class="more-grid"><button class="more-card" data-action="open-backup"><span class="more-icon">☁</span><span>Copias e importación</span></button><button class="more-card" data-action="open-export"><span class="more-icon">⇧</span><span>Exportar viaje</span></button><button class="more-card" data-action="open-settings"><span class="more-icon">⚙</span><span>Ajustes</span></button><button class="more-card" data-action="about"><span class="more-icon">ⓘ</span><span>Sobre TravelBook</span></button></div><section class="section"><h2 class="section-title">Tus datos, contigo</h2><div class="info-note">TravelBook Pro funciona sin cuenta y guarda la información solo en este dispositivo. Descarga una copia antes de cambiar de móvil o borrar los datos de Safari.</div></section>`; }

function tripView() {
  const t = tripById(route.tripId); if (!t) { route = {page:"trips"}; return tripsView(); }
  const tab = route.tab || "days";
  const amount = (t.expenses || []).reduce((s,e)=>s+Number(e.amount || 0),0);
  const content = tab === "days" ? daysPanel(t) : tab === "activities" ? activitiesPanel(t) : expensesPanel(t);
  return `<button class="back" data-page="trips">‹ Volver a viajes</button><section class="detail-hero"><div class="eyebrow">${esc(t.status || "En preparación")}</div><h1>${esc(t.name)}</h1><p>${esc(t.destination || "Destino por definir")} · ${t.start ? `${dateLabel(t.start)} — ${dateLabel(t.end)}` : "Fechas por definir"}</p><p>${(t.days || []).length} días · ${(t.activities || []).length} actividades · ${money(amount)}</p></section><div class="tab-pills"><button class="${tab === "days" ? "active" : ""}" data-action="trip-tab" data-tab="days">Días</button><button class="${tab === "activities" ? "active" : ""}" data-action="trip-tab" data-tab="activities">Actividades</button><button class="${tab === "expenses" ? "active" : ""}" data-action="trip-tab" data-tab="expenses">Gastos</button><button data-action="edit-trip" data-id="${t.id}">Editar</button></div>${content}`;
}
function daysPanel(t) { const days = [...(t.days || [])].sort((a,b)=>(a.date||"").localeCompare(b.date||"")); return `<div class="card">${days.length ? days.map((d,i) => `<div class="day-card"><span class="day-number">Día ${i+1}</span><span class="row-copy"><span class="row-title">${esc(d.title || "Plan del día")}</span><span class="row-sub">${d.date ? dateLabel(d.date) : "Sin fecha"}</span></span><span class="inline-actions"><button data-action="edit-day" data-id="${d.id}">✎</button><button data-action="delete-day" data-id="${d.id}">⌫</button></span></div>`).join("") : `<div class="empty"><span class="empty-icon">▣</span><h3>Planifica los días</h3><p>Añade los días de ${esc(t.name)} y organiza luego las actividades.</p></div>`}<button class="button full" data-action="new-day">+ Añadir día</button></div>`; }
function activitiesPanel(t) { const rows = [...(t.activities || [])].sort((a,b)=>`${a.date}${a.time||""}`.localeCompare(`${b.date}${b.time||""}`)); return `<div class="card activity-list">${rows.length ? rows.map(a => `<div class="activity-row"><span class="round-icon">${iconFor(a.title || "")}</span><div class="row-copy"><div class="row-title">${esc(a.title)}</div><div class="row-sub">${a.date ? shortDate(a.date) : "Sin fecha"}${a.time ? ` · ${esc(a.time)}` : ""}${a.location ? ` · ${esc(a.location)}` : ""}</div></div><span class="inline-actions"><button data-action="edit-activity" data-id="${a.id}">✎</button><button data-action="delete-activity" data-id="${a.id}">⌫</button></span></div>`).join("") : `<div class="empty"><span class="empty-icon">⌾</span><h3>Sin actividades</h3><p>Guarda visitas, reservas, rutas y cualquier plan.</p></div>`}<button class="button full" data-action="new-activity">+ Añadir actividad</button></div>`; }
function expensesPanel(t) { const rows = [...(t.expenses || [])].sort((a,b)=>(b.date||"").localeCompare(a.date||"")); const total=rows.reduce((s,e)=>s+Number(e.amount||0),0); return `<div class="card"><div class="row-sub" style="margin-bottom:8px">Total del viaje <b style="color:var(--ink);font-size:17px">${money(total)}</b></div><div class="expense-list">${rows.length ? rows.map(e => `<div class="expense-row"><span class="round-icon">${iconFor(e.category || "")}</span><div class="row-copy"><div class="row-title">${esc(e.description || e.category || "Gasto")}</div><div class="row-sub">${esc(e.category || "Otros")}${e.date ? ` · ${shortDate(e.date)}` : ""}</div></div><span class="expense-amount">${money(e.amount)}</span><span class="inline-actions"><button data-action="edit-expense" data-id="${e.id}">✎</button><button data-action="delete-expense" data-id="${e.id}">⌫</button></span></div>`).join("") : `<div class="empty"><span class="empty-icon">€</span><h3>Presupuesto bajo control</h3><p>Añade los gastos para tener el total siempre a mano.</p></div>`}</div><button class="button full" data-action="new-expense">+ Añadir gasto</button></div>`; }

function showModal(title, body) { modalLayer.innerHTML = `<section class="modal" role="dialog" aria-modal="true" aria-label="${esc(title)}"><div class="modal-head"><h2>${esc(title)}</h2><button class="close" data-action="close-modal" aria-label="Cerrar">×</button></div>${body}</section>`; modalLayer.hidden = false; setTimeout(() => modalLayer.querySelector("input,select,textarea,button")?.focus(), 50); }
function closeModal() { modalLayer.hidden = true; modalLayer.innerHTML = ""; }
function tripModal(t = null) { const x = t || {name:"",destination:"",start:"",end:"",status:"En preparación",budget:"",notes:""}; showModal(t ? "Editar viaje" : "Nuevo viaje", `<form data-form="trip"><div class="form-grid"><div class="field full"><label>Nombre del viaje *</label><input name="name" required value="${esc(x.name)}" placeholder="Ej. Japón 2026" /></div><div class="field"><label>Destino</label><input name="destination" value="${esc(x.destination)}" placeholder="Ciudad o país" /></div><div class="field"><label>Estado</label><select name="status">${["En preparación","Confirmado","Completado"].map(s=>`<option ${x.status===s?"selected":""}>${s}</option>`).join("")}</select></div><div class="field"><label>Inicio</label><input name="start" type="date" value="${esc(x.start)}" /></div><div class="field"><label>Fin</label><input name="end" type="date" value="${esc(x.end)}" /></div><div class="field"><label>Presupuesto (€)</label><input name="budget" type="number" min="0" step="0.01" value="${esc(x.budget)}" /></div><div class="field full"><label>Notas</label><textarea name="notes" placeholder="Información útil, reservas, ideas…">${esc(x.notes)}</textarea></div></div><div class="form-actions"><button class="button secondary" type="button" data-action="close-modal">Cancelar</button><button class="button" type="submit">${t ? "Guardar cambios" : "Crear viaje"}</button></div></form>`); modalLayer.querySelector("form").dataset.id = t?.id || ""; }
function dayModal(day = null) { const t = tripById(route.tripId); const x = day || {title:"",date:""}; showModal(day ? "Editar día" : "Añadir día", `<form data-form="day"><div class="field"><label>Fecha</label><input name="date" type="date" value="${esc(x.date)}" min="${esc(t.start || "")}" max="${esc(t.end || "")}" /></div><div class="field"><label>Título o plan</label><input name="title" required value="${esc(x.title)}" placeholder="Ej. Llegada y paseo por el centro" /></div><div class="form-actions"><button class="button secondary" type="button" data-action="close-modal">Cancelar</button><button class="button" type="submit">Guardar</button></div></form>`); modalLayer.querySelector("form").dataset.id = day?.id || ""; }
function activityModal(activity = null) { const t = tripById(route.tripId); const x = activity || {title:"",date:"",time:"",location:"",notes:"",dayId:""}; showModal(activity ? "Editar actividad" : "Añadir actividad", `<form data-form="activity"><div class="form-grid"><div class="field full"><label>Actividad *</label><input name="title" required value="${esc(x.title)}" placeholder="Ej. Visita al museo" /></div><div class="field"><label>Fecha</label><input name="date" type="date" value="${esc(x.date)}" /></div><div class="field"><label>Hora</label><input name="time" type="time" value="${esc(x.time)}" /></div><div class="field full"><label>Ubicación</label><input name="location" value="${esc(x.location)}" placeholder="Dirección, barrio o ciudad" /></div>${(t.days||[]).length ? `<div class="field full"><label>Asociar a un día (opcional)</label><select name="dayId"><option value="">Sin asociar</option>${t.days.map(d=>`<option value="${d.id}" ${x.dayId===d.id?"selected":""}>${esc(d.title || dateLabel(d.date))}</option>`).join("")}</select></div>` : ""}<div class="field full"><label>Notas</label><textarea name="notes">${esc(x.notes)}</textarea></div></div><div class="form-actions"><button class="button secondary" type="button" data-action="close-modal">Cancelar</button><button class="button" type="submit">Guardar</button></div></form>`); modalLayer.querySelector("form").dataset.id = activity?.id || ""; }
function expenseModal(expense = null) { const x = expense || {description:"",amount:"",category:"Alojamiento",date:"",notes:""}; const categories=["Alojamiento","Transporte","Gasolina","Parking","Peajes","Tasas","Comida","Bebidas","Entradas","Supermercado","Souvenirs","Compras","Otros"]; showModal(expense ? "Editar gasto" : "Añadir gasto", `<form data-form="expense"><div class="form-grid"><div class="field full"><label>Concepto *</label><input name="description" required value="${esc(x.description)}" placeholder="Ej. Hotel, cena, taxi…" /></div><div class="field"><label>Importe (€) *</label><input name="amount" required type="number" min="0" step="0.01" value="${esc(x.amount)}" /></div><div class="field"><label>Categoría</label><select name="category">${categories.map(c=>`<option ${x.category===c?"selected":""}>${c}</option>`).join("")}</select></div><div class="field"><label>Fecha</label><input name="date" type="date" value="${esc(x.date)}" /></div><div class="field full"><label>Notas</label><textarea name="notes">${esc(x.notes)}</textarea></div></div><div class="form-actions"><button class="button secondary" type="button" data-action="close-modal">Cancelar</button><button class="button" type="submit">Guardar</button></div></form>`); modalLayer.querySelector("form").dataset.id = expense?.id || ""; }

function settingsModal() { showModal("Ajustes", `<div class="modal-section"><h3>Funcionamiento sin conexión</h3><p>La aplicación se guarda para funcionar sin internet después de abrirla una vez desde un servidor HTTPS.</p></div><div class="modal-section"><h3>Datos locales</h3><p>Tu información se mantiene exclusivamente en este navegador.</p><button class="button danger full" data-action="clear-data">Eliminar todos los datos</button></div>`); }
function backupModal() { showModal("Copias e importación", `<div class="modal-section"><h3>Descargar copia</h3><p>Guarda todos tus viajes, actividades y gastos en un archivo JSON.</p><button class="button full" data-action="download-backup">⇩ Descargar copia de seguridad</button></div><div class="modal-section"><h3>Restaurar una copia</h3><p>Importa un archivo JSON creado por TravelBook. Sustituirá los datos actuales.</p><label class="button secondary full" for="importFile">⇧ Elegir archivo de copia</label><input class="file-input" id="importFile" type="file" accept="application/json,.json" /></div>`); }
function exportModal() { const options = data.trips.map(t=>`<option value="${t.id}">${esc(t.name)}</option>`).join(""); showModal("Exportar viaje", data.trips.length ? `<div class="modal-section"><h3>Elige un viaje</h3><p>CSV se abre directamente con Excel. Para PDF se abre la vista de impresión del navegador.</p><select id="exportTrip">${options}</select></div><div class="form-actions"><button class="button secondary" data-action="export-csv">Excel (CSV)</button><button class="button" data-action="export-pdf">PDF / imprimir</button></div>` : `<div class="empty"><span class="empty-icon">⇧</span><h3>No hay viajes para exportar</h3><p>Crea primero un viaje.</p></div>`); }
function aboutModal() { showModal("TravelBook Pro", `<div class="info-note">TravelBook Pro Mobile v1.0<br><br>Tu diario de viajes, diseñado para pantalla táctil. Funciona sin cuenta y tus datos se quedan en tu dispositivo.</div>`); }

function handleForm(form) { const values = Object.fromEntries(new FormData(form)); const kind=form.dataset.form, id=form.dataset.id; if (kind === "trip") { const existing=tripById(id); const next={ ...values, budget:Number(values.budget || 0), id:existing?.id||uid(), days:existing?.days||[], activities:existing?.activities||[], expenses:existing?.expenses||[], created:existing?.created||new Date().toISOString() }; if (next.start && next.end && next.end < next.start) return toast("La fecha final no puede ser anterior al inicio."); if(existing) Object.assign(existing,next); else data.trips.push(next); save(); closeModal(); route={page:"trip",tripId:next.id,tab:"days"}; toast(existing?"Viaje actualizado":"Viaje creado"); }
  else { const t=tripById(route.tripId); if(!t) return; if(kind === "day") { const arr=t.days ||= []; const item={...values,id:id||uid()}; const old=arr.find(x=>x.id===id); old?Object.assign(old,item):arr.push(item); } if(kind === "activity") { const arr=t.activities ||= []; const item={...values,id:id||uid()}; const old=arr.find(x=>x.id===id); old?Object.assign(old,item):arr.push(item); } if(kind === "expense") { const arr=t.expenses ||= []; const item={...values,amount:Number(values.amount||0),id:id||uid()}; const old=arr.find(x=>x.id===id); old?Object.assign(old,item):arr.push(item); } save(); closeModal(); toast("Datos guardados"); } render(); }

function deleteItem(type, id) { const t=tripById(route.tripId); if(!t) return; if(!confirm("¿Quieres eliminar este elemento?")) return; const collection=type === "day" ? "days" : type === "activity" ? "activities" : "expenses"; t[collection]=(t[collection]||[]).filter(x=>x.id!==id); if(type === "day") (t.activities||[]).forEach(a=>{if(a.dayId===id) a.dayId=""}); save(); render(); toast("Elemento eliminado"); }
function download(filename, contents, type="application/json") { const a=document.createElement("a"); a.href=URL.createObjectURL(new Blob([contents],{type})); a.download=filename; document.body.append(a); a.click(); setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},250); }
function makeBackup() { download(`TravelBookPro_copia_${new Date().toISOString().slice(0,10)}.json`, JSON.stringify(data,null,2)); toast("Copia descargada"); }
function importBackup(file) { const reader=new FileReader(); reader.onload=()=>{ try { const imported=JSON.parse(reader.result); if(!imported || !Array.isArray(imported.trips)) throw Error(); if(!confirm("La restauración reemplazará los datos actuales. ¿Continuar?")) return; data={version:1,trips:imported.trips.map(t=>({...t,days:t.days||[],activities:t.activities||[],expenses:t.expenses||[]}))}; save(); closeModal(); route={page:"dashboard"}; render(); toast("Copia restaurada correctamente"); } catch (_) { toast("Ese archivo no parece una copia válida de TravelBook."); } }; reader.readAsText(file); }
function exportCsv(trip) { const q = v => `"${String(v ?? "").replace(/"/g,'""')}"`; const rows=[["TravelBook Pro",trip.name],["Destino",trip.destination],["Inicio",trip.start],["Fin",trip.end],[],["Días"],["Fecha","Título"],...(trip.days||[]).map(d=>[d.date,d.title]),[],["Actividades"],["Fecha","Hora","Actividad","Ubicación","Notas"],...(trip.activities||[]).map(a=>[a.date,a.time,a.title,a.location,a.notes]),[],["Gastos"],["Fecha","Categoría","Concepto","Importe (€)","Notas"],...(trip.expenses||[]).map(e=>[e.date,e.category,e.description,Number(e.amount||0).toFixed(2),e.notes])]; download(`TravelBookPro_${safeName(trip.name)}.csv`, "\ufeff"+rows.map(row=>row.map(q).join(";")).join("\n"), "text/csv;charset=utf-8"); toast("Archivo para Excel descargado"); }
function safeName(value) { return String(value||"viaje").replace(/[^a-z0-9áéíóúñ]+/gi,"_").replace(/^_|_$/g,""); }
function exportPdf(trip) { closeModal(); route={page:"trip",tripId:trip.id,tab:"days"}; render(); setTimeout(()=>{window.print();toast("En la impresión puedes guardar o compartir como PDF.")},250); }

document.addEventListener("click", event => { const button=event.target.closest("[data-action], [data-page]"); if(!button) return; const action=button.dataset.action; if(button.dataset.page) { route={page:button.dataset.page,tripId:null,tab:"days"}; render(); return; } const id=button.dataset.id; const t=tripById(route.tripId); if(action === "close-modal") closeModal(); else if(action === "new-trip") tripModal(); else if(action === "edit-trip") tripModal(tripById(id)); else if(action === "open-trip") { route={page:"trip",tripId:id,tab:"days"};render(); } else if(action === "trip-tab") {route.tab=button.dataset.tab;render()} else if(action === "new-day") dayModal(); else if(action === "edit-day") dayModal((t.days||[]).find(x=>x.id===id)); else if(action === "delete-day") deleteItem("day",id); else if(action === "new-activity") activityModal(); else if(action === "edit-activity") activityModal((t.activities||[]).find(x=>x.id===id)); else if(action === "delete-activity") deleteItem("activity",id); else if(action === "new-expense") expenseModal(); else if(action === "edit-expense") expenseModal((t.expenses||[]).find(x=>x.id===id)); else if(action === "delete-expense") deleteItem("expense",id); else if(action === "go-trips") {route={page:"trips"};render()} else if(action === "open-settings") settingsModal(); else if(action === "open-backup") backupModal(); else if(action === "open-export") exportModal(); else if(action === "about") aboutModal(); else if(action === "download-backup") makeBackup(); else if(action === "clear-data") { if(confirm("Esta acción elimina todos los viajes guardados en este dispositivo. ¿Continuar?")){data=structuredClone(initialData);save();closeModal();route={page:"dashboard"};render();toast("Datos eliminados");} } else if(action === "export-csv") {const x=tripById(document.querySelector("#exportTrip").value);if(x)exportCsv(x)} else if(action === "export-pdf") {const x=tripById(document.querySelector("#exportTrip").value);if(x)exportPdf(x)} });
document.addEventListener("submit", event => { if(event.target.matches("form[data-form]")){event.preventDefault();handleForm(event.target)} });
document.addEventListener("change", event => { if(event.target.id === "importFile" && event.target.files[0]) importBackup(event.target.files[0]); });
modalLayer.addEventListener("click", event => { if(event.target === modalLayer) closeModal(); });
document.addEventListener("click", event => { const filter=event.target.closest("[data-filter]"); if(!filter) return; document.querySelectorAll("[data-filter]").forEach(b=>b.classList.toggle("active",b===filter));document.querySelectorAll("[data-trip-status]").forEach(card=>card.hidden=filter.dataset.filter!=="all"&&card.dataset.tripStatus!==filter.dataset.filter); });

window.addEventListener("beforeinstallprompt", event => { event.preventDefault(); deferredInstall=event; document.querySelector("#installButton").hidden=false; });
document.querySelector("#installButton").addEventListener("click", async () => { if(!deferredInstall) return; deferredInstall.prompt(); await deferredInstall.userChoice; deferredInstall=null; document.querySelector("#installButton").hidden=true; });
if("serviceWorker" in navigator) window.addEventListener("load", () => navigator.serviceWorker.register("./service-worker.js").catch(() => {}));
render();
